### ISSUE TITLE
Cannot use lvg module to simply extend a volume group with a new device

### ISSUE THREAD

**Issue by bhirsch70** [bhirsch70/Ansible-LVM#1]
Received the following error when running.  Worth noting that /dev/vda2 is the device that already exists in the "rhel" volume group.  I'm simply trying to add a new device to the rhel vg, but I'm not sure lvg supports that.

lvg:
   vg: "{{ rhel7_vg }}"
   pvs: "{{ new_disk }}"
  
TASK [create_filesystem : Create Phyiscal Volume (PV) and extend Volume Group (VG)] ***
fatal: [atc5-disk]: FAILED! => {"changed": false, "err": "  Physical volume \"/dev/vda2\" still in use\n", "failed": true, "msg": "Unable to reduce rhel by /dev/vda2.", "rc": 5}

**Comment by wtcross** [comment]
@bhirsch70 did you figure this out? If not I can investigate.

**Comment by bhirsch70** [comment]
No I didn't get this solved.

**Comment by wtcross** [comment]
Did you try this when the device was unmounted?

**Comment by bhirsch70** [comment]
No, when I attempted this, the device didn't even have a file system on it yet.  If I'm reading the doc/example correctly, that module with those arguments should have extended the VG with /dev/vda2.  But you just gave me an idea.  I'm going to try the same thing with 
```yaml
state: present
```
since it appears it's trying to reduce the VG.

**Comment by bhirsch70** [comment]
Solved it, just don't like exactly how I solved it.  Apparently, you have to specify all devices in the VG, including the ones that already exist.  For example, my ```rhel``` volume group already has the device ```/dev/vda2``` in it and I want to add ```/dev/vdb1```.

```yaml
- name: Extend Volume Group
      lvg:
        vg: rhel
        pvs: /dev/vda2,/dev/vdb1
```

This means that if we want to use that module, we need to discover and register the existing devices per/VG and specify them in our task.  Doable I guess, but extra work that the system command doesn't require.
